# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: make install
      - run:
          name: "Testing the code submitted"
          command: "make accept"
      - store_artifacts:
          path: .
  build-master:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: make install
      - run:
          name: "Testing the example submit"
          command: "make submit solution-file=solution/example-A.c"
      - run:
          name: "Testing the example accept"
          command: "make accept"
      - store_artifacts:
          path: .
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
              branches:
                  ignore:
                      - master
      - build-master:
          filters:
              branches:
                  only:
                      - master
